# Generated by Django 5.1.4 on 2025-01-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='id',
            new_name='user',
        ),
    ]
