# Generated by Django 5.1.4 on 2025-01-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndio_app', '0004_payment_delete_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='date',
        ),
    ]
