# Generated by Django 5.1.4 on 2025-01-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndio_app', '0005_rename_created_at_payment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
