# Generated by Django 5.1.4 on 2025-01-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndio_app', '0008_remove_payment_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
    ]
