# Generated by Django 5.1.4 on 2025-01-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndio_app', '0009_remove_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
