# Generated by Django 5.1.4 on 2025-01-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndio_app', '0010_alter_payment_payment_id_alter_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
