# Generated by Django 5.1.4 on 2025-02-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0017_alter_user_detail_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_detail",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
