# Generated by Django 5.1.4 on 2025-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0020_userdetail_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkprovider",
            name="guid_network_provider_id",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
