# Generated by Django 5.1.4 on 2025-03-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0021_alter_networkprovider_guid_network_provider_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkprovider",
            name="guid_network_provider_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="networkprovider",
            name="name",
            field=models.CharField(max_length=60),
        ),
    ]
