# Generated by Django 5.1.4 on 2025-03-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0022_alter_networkprovider_guid_network_provider_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fibreproduct",
            name="product_id",
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
