# Generated by Django 5.1.4 on 2025-03-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0024_alter_fibreproduct_network_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fibreproduct",
            name="network_provider",
            field=models.ForeignKey(
                default="null",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="ndio_app.networkprovider",
            ),
            preserve_default=False,
        ),
    ]
