# Generated by Django 5.1.4 on 2025-03-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0025_alter_fibreproduct_network_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fibreproduct",
            name="product_id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
