# Generated by Django 5.1.4 on 2025-03-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0026_alter_fibreproduct_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fibreproduct",
            name="product_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="order",
            name="address_type",
            field=models.CharField(max_length=150),
        ),
    ]
