# Generated by Django 5.1.4 on 2025-03-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0028_alter_userdetail_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="order",
            name="address_type",
            field=models.CharField(max_length=50),
        ),
    ]
