# Generated by Django 5.1.4 on 2025-03-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0029_alter_order_address_alter_order_address_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="province",
            field=models.CharField(default="other", max_length=150),
            preserve_default=False,
        ),
    ]
