# Generated by Django 5.1.4 on 2025-04-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0034_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicesContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                ("surname", models.CharField(max_length=50, null=True)),
                ("email", models.CharField(max_length=100, null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                ("service", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
