# Generated by Django 5.1.4 on 2025-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0035_servicescontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicescontact",
            name="descriptions",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="servicescontact",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
