# Generated by Django 5.1.4 on 2025-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0036_servicescontact_descriptions_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicescontact",
            old_name="descriptions",
            new_name="description",
        ),
        migrations.AddField(
            model_name="servicescontact",
            name="company_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
