# Generated by Django 5.1.4 on 2025-05-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0037_rename_descriptions_servicescontact_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="id_number",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
