# Generated by Django 5.1.4 on 2025-05-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0038_alter_userdetail_id_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
