# Generated by Django 5.1.4 on 2025-05-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0040_fibreproduct_product_speed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fibreproduct",
            name="product_speed",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
