# Generated by Django 5.1.4 on 2025-05-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ndio_app", "0041_alter_fibreproduct_product_speed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fibreproduct",
            old_name="price",
            new_name="product_price",
        ),
    ]
